server:
  port: 8088

logging:
  level:
    root: info


spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://39.98.163.208:3306/empdoc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Password_bishe132
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ynet.empdoc.entity